### ISSUE TITLE
get_dr_py/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by xiaobaozi1996** [QianyiWu/get_dr_py#3]
请问如何解决,这个好像是系统默认的python版本是2.7的,这个里边要求是3.5的

**Comment by QianyiWu** [comment]
你好，如果是想指定具体使用的系统的Python版本的话，可以在CMakeLists.txt里加上：
`set(PYTHON_LIBRARIES` `"/usr/lib/x86_64-linux-gnu/libpython2.7.a")
set(PYTHON_INCLUDE_DIR "/usr/include/python2.7")`
 然后重新编译试试看

**Comment by QianyiWu** [comment]
你好，如果是想指定具体使用的系统的Python版本的话，可以在CMakeLists.txt里加上： set(PYTHON_LIBRARIES``` "/usr/lib/x86_64-linux-gnu/libpython2.7.a") 
set(PYTHON_INCLUDE_DIR "/usr/include/python2.7")
然后重新编译试试看
